"""Confluence library exports, loaded on first use; CLI discovery stays lightweight."""

from __future__ import annotations

from importlib import import_module

__version__ = "2.0.0"

_EXPORTS = {
    "BatchConfig": ("assistant_skills_lib.batch_processor", "BatchConfig"),
    "BatchProcessor": ("assistant_skills_lib.batch_processor", "BatchProcessor"),
    "BatchProgress": ("assistant_skills_lib.batch_processor", "BatchProgress"),
    "CheckpointManager": ("assistant_skills_lib.batch_processor", "CheckpointManager"),
    "generate_operation_id": (
        "assistant_skills_lib.batch_processor",
        "generate_operation_id",
    ),
    "get_recommended_batch_size": (
        "assistant_skills_lib.batch_processor",
        "get_recommended_batch_size",
    ),
    "list_pending_checkpoints": (
        "assistant_skills_lib.batch_processor",
        "list_pending_checkpoints",
    ),
    "Cache": ("assistant_skills_lib.cache", "Cache"),
    "cached": ("assistant_skills_lib.cache", "cached"),
    "get_cache": ("assistant_skills_lib.cache", "get_cache"),
    "invalidate": ("assistant_skills_lib.cache", "invalidate"),
    "BatchError": ("assistant_skills_lib.request_batcher", "BatchError"),
    "BatchResult": ("assistant_skills_lib.request_batcher", "BatchResult"),
    "RequestBatcher": ("assistant_skills_lib.request_batcher", "RequestBatcher"),
    "adf_to_markdown": ("confluence_as.adf_helper", "adf_to_markdown"),
    "adf_to_text": ("confluence_as.adf_helper", "adf_to_text"),
    "create_adf_doc": ("confluence_as.adf_helper", "create_adf_doc"),
    "create_blockquote": ("confluence_as.adf_helper", "create_blockquote"),
    "create_bullet_list": ("confluence_as.adf_helper", "create_bullet_list"),
    "create_code_block": ("confluence_as.adf_helper", "create_code_block"),
    "create_heading": ("confluence_as.adf_helper", "create_heading"),
    "create_link": ("confluence_as.adf_helper", "create_link"),
    "create_ordered_list": ("confluence_as.adf_helper", "create_ordered_list"),
    "create_paragraph": ("confluence_as.adf_helper", "create_paragraph"),
    "create_rule": ("confluence_as.adf_helper", "create_rule"),
    "create_table": ("confluence_as.adf_helper", "create_table"),
    "create_text": ("confluence_as.adf_helper", "create_text"),
    "is_markdown_block_start": ("confluence_as.adf_helper", "is_markdown_block_start"),
    "markdown_to_adf": ("confluence_as.adf_helper", "markdown_to_adf"),
    "text_to_adf": ("confluence_as.adf_helper", "text_to_adf"),
    "validate_adf": ("confluence_as.adf_helper", "validate_adf"),
    "AutocompleteCache": ("confluence_as.autocomplete_cache", "AutocompleteCache"),
    "get_autocomplete_cache": (
        "confluence_as.autocomplete_cache",
        "get_autocomplete_cache",
    ),
    "ConfigManager": ("confluence_as.config_manager", "ConfigManager"),
    "get_confluence_client": ("confluence_as.config_manager", "get_confluence_client"),
    "ConfluenceClient": ("confluence_as.confluence_client", "ConfluenceClient"),
    "create_client": ("confluence_as.confluence_client", "create_client"),
    "ConfluenceCredentialManager": (
        "confluence_as.credential_manager",
        "ConfluenceCredentialManager",
    ),
    "CredentialBackend": ("confluence_as.credential_manager", "CredentialBackend"),
    "CredentialNotFoundError": (
        "confluence_as.credential_manager",
        "CredentialNotFoundError",
    ),
    "get_credential_manager": (
        "confluence_as.credential_manager",
        "get_credential_manager",
    ),
    "get_credentials": ("confluence_as.credential_manager", "get_credentials"),
    "is_keychain_available": (
        "confluence_as.credential_manager",
        "is_keychain_available",
    ),
    "store_credentials": ("confluence_as.credential_manager", "store_credentials"),
    "validate_credentials": (
        "confluence_as.credential_manager",
        "validate_credentials",
    ),
    "AuthenticationError": ("confluence_as.error_handler", "AuthenticationError"),
    "ConflictError": ("confluence_as.error_handler", "ConflictError"),
    "ConfluenceError": ("confluence_as.error_handler", "ConfluenceError"),
    "ErrorContext": ("confluence_as.error_handler", "ErrorContext"),
    "NotFoundError": ("confluence_as.error_handler", "NotFoundError"),
    "PermissionError": ("confluence_as.error_handler", "PermissionError"),
    "RateLimitError": ("confluence_as.error_handler", "RateLimitError"),
    "ServerError": ("confluence_as.error_handler", "ServerError"),
    "ValidationError": ("confluence_as.error_handler", "ValidationError"),
    "extract_error_message": ("confluence_as.error_handler", "extract_error_message"),
    "handle_confluence_error": (
        "confluence_as.error_handler",
        "handle_confluence_error",
    ),
    "handle_errors": ("confluence_as.error_handler", "handle_errors"),
    "print_error": ("confluence_as.error_handler", "print_error"),
    "sanitize_error_message": ("confluence_as.error_handler", "sanitize_error_message"),
    "Colors": ("confluence_as.formatters", "Colors"),
    "export_csv": ("confluence_as.formatters", "export_csv"),
    "format_attachment": ("confluence_as.formatters", "format_attachment"),
    "format_blogpost": ("confluence_as.formatters", "format_blogpost"),
    "format_comment": ("confluence_as.formatters", "format_comment"),
    "format_comments": ("confluence_as.formatters", "format_comments"),
    "format_json": ("confluence_as.formatters", "format_json"),
    "format_label": ("confluence_as.formatters", "format_label"),
    "format_page": ("confluence_as.formatters", "format_page"),
    "format_search_results": ("confluence_as.formatters", "format_search_results"),
    "format_space": ("confluence_as.formatters", "format_space"),
    "format_table": ("confluence_as.formatters", "format_table"),
    "format_timestamp": ("confluence_as.formatters", "format_timestamp"),
    "format_version": ("confluence_as.formatters", "format_version"),
    "print_info": ("confluence_as.formatters", "print_info"),
    "print_success": ("confluence_as.formatters", "print_success"),
    "print_warning": ("confluence_as.formatters", "print_warning"),
    "strip_html_tags": ("confluence_as.formatters", "strip_html_tags"),
    "truncate": ("confluence_as.formatters", "truncate"),
    "is_block_start": ("confluence_as.markdown_parser", "is_block_start"),
    "parse_markdown": ("confluence_as.markdown_parser", "parse_markdown"),
    "SpaceContext": ("confluence_as.space_context", "SpaceContext"),
    "clear_context_cache": ("confluence_as.space_context", "clear_context_cache"),
    "format_context_summary": ("confluence_as.space_context", "format_context_summary"),
    "get_common_labels": ("confluence_as.space_context", "get_common_labels"),
    "get_page_defaults": ("confluence_as.space_context", "get_page_defaults"),
    "get_space_context": ("confluence_as.space_context", "get_space_context"),
    "get_top_contributors": ("confluence_as.space_context", "get_top_contributors"),
    "has_space_context": ("confluence_as.space_context", "has_space_context"),
    "suggest_parent_page": ("confluence_as.space_context", "suggest_parent_page"),
    "validate_attachment_id": ("confluence_as.validators", "validate_attachment_id"),
    "validate_content_type": ("confluence_as.validators", "validate_content_type"),
    "validate_cql": ("confluence_as.validators", "validate_cql"),
    "validate_email": ("confluence_as.validators", "validate_email"),
    "validate_file_path": ("confluence_as.validators", "validate_file_path"),
    "validate_issue_key": ("confluence_as.validators", "validate_issue_key"),
    "validate_jql_query": ("confluence_as.validators", "validate_jql_query"),
    "validate_label": ("confluence_as.validators", "validate_label"),
    "validate_limit": ("confluence_as.validators", "validate_limit"),
    "validate_page_id": ("confluence_as.validators", "validate_page_id"),
    "validate_space_key": ("confluence_as.validators", "validate_space_key"),
    "validate_title": ("confluence_as.validators", "validate_title"),
    "validate_url": ("confluence_as.validators", "validate_url"),
    "adf_to_xhtml": ("confluence_as.xhtml_helper", "adf_to_xhtml"),
    "extract_text_from_xhtml": (
        "confluence_as.xhtml_helper",
        "extract_text_from_xhtml",
    ),
    "markdown_to_xhtml": ("confluence_as.xhtml_helper", "markdown_to_xhtml"),
    "validate_xhtml": ("confluence_as.xhtml_helper", "validate_xhtml"),
    "wrap_in_storage_format": ("confluence_as.xhtml_helper", "wrap_in_storage_format"),
    "xhtml_to_adf": ("confluence_as.xhtml_helper", "xhtml_to_adf"),
    "xhtml_to_markdown": ("confluence_as.xhtml_helper", "xhtml_to_markdown"),
}

__all__ = [
    "__version__",
    "BatchConfig",
    "BatchProcessor",
    "BatchProgress",
    "CheckpointManager",
    "generate_operation_id",
    "get_recommended_batch_size",
    "list_pending_checkpoints",
    "BatchError",
    "BatchResult",
    "RequestBatcher",
    "ConfluenceClient",
    "create_client",
    "ConfigManager",
    "get_confluence_client",
    "ConfluenceCredentialManager",
    "CredentialBackend",
    "CredentialNotFoundError",
    "get_credential_manager",
    "get_credentials",
    "is_keychain_available",
    "store_credentials",
    "validate_credentials",
    "ConfluenceError",
    "AuthenticationError",
    "PermissionError",
    "ValidationError",
    "NotFoundError",
    "RateLimitError",
    "ConflictError",
    "ServerError",
    "handle_confluence_error",
    "handle_errors",
    "print_error",
    "sanitize_error_message",
    "extract_error_message",
    "ErrorContext",
    "validate_attachment_id",
    "validate_page_id",
    "validate_space_key",
    "validate_cql",
    "validate_content_type",
    "validate_file_path",
    "validate_url",
    "validate_email",
    "validate_title",
    "validate_label",
    "validate_limit",
    "validate_issue_key",
    "validate_jql_query",
    "Colors",
    "format_page",
    "format_blogpost",
    "format_space",
    "format_comment",
    "format_comments",
    "format_search_results",
    "format_table",
    "format_json",
    "format_timestamp",
    "format_attachment",
    "format_label",
    "format_version",
    "export_csv",
    "print_success",
    "print_warning",
    "print_info",
    "truncate",
    "strip_html_tags",
    "parse_markdown",
    "is_block_start",
    "create_adf_doc",
    "create_paragraph",
    "create_text",
    "create_heading",
    "create_bullet_list",
    "create_ordered_list",
    "create_code_block",
    "create_blockquote",
    "create_rule",
    "create_table",
    "create_link",
    "text_to_adf",
    "markdown_to_adf",
    "adf_to_text",
    "adf_to_markdown",
    "validate_adf",
    "is_markdown_block_start",
    "xhtml_to_markdown",
    "markdown_to_xhtml",
    "xhtml_to_adf",
    "adf_to_xhtml",
    "extract_text_from_xhtml",
    "wrap_in_storage_format",
    "validate_xhtml",
    "Cache",
    "get_cache",
    "cached",
    "invalidate",
    "AutocompleteCache",
    "get_autocomplete_cache",
    "SpaceContext",
    "get_space_context",
    "clear_context_cache",
    "has_space_context",
    "get_page_defaults",
    "get_common_labels",
    "get_top_contributors",
    "suggest_parent_page",
    "format_context_summary",
]


def __getattr__(name: str):
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module, symbol = _EXPORTS[name]
    value = getattr(import_module(module), symbol)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(__all__))
